### PR TITLE
Add integer value constraint checking for PER encoding

### PR DESCRIPTION
**Pull request by shahn**
This fixes issue #286.

### CODE REVIEW

**Comment by shahn** [comment]
The failures look like clippy warnings that I did not introduce, but I have added a commit to fix them

**Comment by shahn** [comment]
I am honestly a bit confused about these CI failures, now I see a failure in rasn-pkix for example. I will work on fixing them as well, but I did not touch any code over there.

**Comment by XAMPPRocky** [comment]
I think the CI should probably be adjusted to have clippy only run on stable.

**Comment by shahn** [comment]
I hope I did it right above :)

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
